<a href="https://colab.research.google.com/github/RaquelMichelon/Linear_Algebra_Numpy_Studies/blob/main/Numpy_Arrays_and_Matrices_LSU12_Week7_LDSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Studies: Arrays and Matrices with Numpy

---



## Arrays

In [3]:
import numpy as np

In [4]:
print? #the docstring will appear on the right corner

SyntaxError: ignored

In [5]:
#ndarray is a colection of items of the same size and types

#create an array to represent a vector, using np.array():
u = [0, 1, 2]
a = np.ndarray(u)
a

array([], shape=(0, 1, 2), dtype=float64)

In [6]:
#create a table of numbers (a matrix) from a list of lists, using np.array()

b = np.array([[0, 1, 2], 
                [3, 4, 5], 
                [6, 7, 8]])

print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#Number of array dimensions

a = np.array([0, 1, 2]) #3-dimension row vector
a.ndim # number of array dimension = 1 because we can store it in an 1D array

1

In [8]:
b.ndim #b is an 2D array

2

In [9]:
#accessing first row in b

b[0]

array([0, 1, 2])

In [10]:
#accessing second element in the first row in b
b[0][1]

1

In [11]:
# Represent a row vector vs. its transpose in an ndarray

a = np.array([[0],
              [1],
              [2]])  # a 2D numpy array, a 3-dimensional COLUMN vector
a.ndim  # number of array dimensions

2

In [12]:
#notice the difference

# this is a 1D array
np.array([0, 1, 2])

array([0, 1, 2])

In [13]:
#and this is an 2D array
np.array([[0, 1, 2]])

array([[0, 1, 2]])

In [14]:
#Shape of an array is a tuple of integers

a = np.array([[0],
              [1],
              [2]])  # same vector as in the last code cell
a.shape  # shape of the array (number of elements in axis 0, number of elements in axis 1)



(3, 1)

* The underlying class which creates the NumPy array is the class numpy.ndarray. However, it is advisable to construct arrays using its built-in functions, such as array, zeros or ones

In [15]:
#Vectors and linear algebra using NumPy

#Representing vectors with ndarrays: transpose, reshape()

In [16]:
a = np.array([[0], 
              [1], 
              [2], 
              [3]])  # a 4-dimensional column vector
print("a:\n", a, "\n")
print("a.shape:", a.shape)
print("a.ndim:", a.ndim)

a:
 [[0]
 [1]
 [2]
 [3]] 

a.shape: (4, 1)
a.ndim: 2


In [17]:
#attribute .T (for transpose)

a_T = a.T  # the transpose of a
print("a_T:", a_T, "\n")
print("a_T.shape:", a_T.shape)
print("a_T.ndim:", a.ndim)

a_T: [[0 1 2 3]] 

a_T.shape: (1, 4)
a_T.ndim: 2


In [18]:
#1D array

print("shape of 1D array: ", np.array([0,1,2,3]).shape)
print("shape of the transpose of 1D array: ", np.array([0,1,2,3]).T.shape)

shape of 1D array:  (4,)
shape of the transpose of 1D array:  (4,)


In [19]:
#reshape method allows you to reshape an array of data to any given shape

array_1d = np.array([0, 1, 2, 3, 4, 5])  # 1-dimensional array, with 6 elements, shape is (6, )
print(array_1d)
print("shape: ", array_1d.shape)

[0 1 2 3 4 5]
shape:  (6,)


In [20]:
array_reshaped = array_1d.reshape((3, 2))  # reshape to a table!
print(array_reshaped)
print("shape: ", array_reshaped.shape)

[[0 1]
 [2 3]
 [4 5]]
shape:  (3, 2)


In [21]:
try:
    array_1d.reshape((4, 2))
except ValueError as e:
    print("ValueError:", e)

ValueError: cannot reshape array of size 6 into shape (4,2)


In [22]:
#Creating row and column vectors with reshape()

a = np.array([0,1,2,3])  # vector represented by a 1D array
a.shape  # shape of array a

(4,)

In [23]:
a_row = a.reshape((1, -1))  # use reshape to get a 2D array representation of a row vector
print("a_row:\n", a_row, "\n")
print("a_row.shape:", a_row.shape)

a_row:
 [[0 1 2 3]] 

a_row.shape: (1, 4)


In [24]:
a_column = a.reshape((-1, 1))  # use reshape to get a 2D array representation of a column vector
print("a_column:\n", a_column, "\n")
print("a_column.shape:", a_column.shape)

a_column:
 [[0]
 [1]
 [2]
 [3]] 

a_column.shape: (4, 1)


In [25]:
#Because we now have our vector in a 2D array, we could use the transpose attribute safely:

# same result
print(a_column.T)

[[0 1 2 3]]


In [26]:
#NumPy also has a module called numpy.linalg, which is entirely dedicated to linear algebra operations

#Vector norm using numpy.linalg.norm()

np.linalg.norm?

In [27]:
#determine the norm of the vector
a = np.array([[-1],
              [2]])
np.linalg.norm(a)

2.23606797749979

In [28]:
# np.sqrt() computes the square root value of its input
np.sqrt(5)

2.23606797749979

In [29]:
#Vector operations (multiplication by scalars and addition)

# let's create two ndarrays representing 4-dimensional vectors
u = np.array([1, 0, 1, 1])
v = np.array([1, -2, 0, 1])

# print vectors to check your lucky numbers
print(f"u = {u}")
print(f"v = {v}\n")


u = [1 0 1 1]
v = [ 1 -2  0  1]



In [30]:
# multiplication by a scalar
-(1/2) * u

array([-0.5, -0. , -0.5, -0.5])

In [31]:
# addition
u + v

array([ 2, -2,  1,  2])

In [32]:
# linear combination
(-(1/2) * u)  + (1 * v)

array([ 0.5, -2. , -0.5,  0.5])

In [33]:
#Dot product

#numpy.dot to determine the dot product of two vectors

# create two vectors using numpy arrays
u = np.array([-1, 2, 2])  # row vector, 1D array
v = np.array([-2, 1, 1])  # row vector, 1D array

# determine the dot product between vectors u and v
np.dot(u, v)

6

In [34]:
# create two vectors using numpy arrays
u = np.array([-1, 2, 2]).reshape((1, 3))  # row vector, 2D array
v = np.array([-2, 1, 1])  # row vector, 1D array

# determine the dot product between vectors u and v
np.dot(u, v)

array([6])

In [35]:
# let's check those results "by hand", because we love linear algebra!
((-1) * (-2)) + (2 * 1) + (2 * 1)

6

## Matrices


In [36]:
# a 2x3 matrix
A = np.array([
    [2, 0.1, -1],
    [3, 1/5, np.sqrt(2)]  # np.sqrt(2) is the square root of 2; np.sqrt() can also be used for arrays
])

# a 2x3 matrix
B = np.array([[-2, -2, 1],
              [0, 1, 1]])

# show our matrices
print("A\n:", A, "\n")
print("B\n:", B)

A
: [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]] 

B
: [[-2 -2  1]
 [ 0  1  1]]


In [37]:
# print shape and number of dimensions of array A
print("A.shape:", A.shape)
print("A.ndim:", A.ndim)

# print shape and number of dimensions of array B
print("B.shape:", B.shape)
print("B.ndim:", B.ndim)

A.shape: (2, 3)
A.ndim: 2
B.shape: (2, 3)
B.ndim: 2


In [38]:
# The shape of array A is (2, 3)...  that's the dimension of the matrix , 2x3

In [39]:
# Special matrices

# a zero matrix of size 4x2
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
# identity matrix of size 5x5 (also is square & diagonal),
# represented by an array (shape = (5, 5))
I = np.identity(5)  # the input is the number of rows (or columns)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
#  Matrix operations

#Multiplication by a scalar

print("Matrix B:")
print(B)

Matrix B:
[[-2 -2  1]
 [ 0  1  1]]


In [42]:
0.5 * B  # simply use the Python multiplication operator *


array([[-1. , -1. ,  0.5],
       [ 0. ,  0.5,  0.5]])

In [43]:
#Addition (and subtraction) of matrices

print("Matrix A:\n", A, "\n")
print("Matrix B:\n", B)

Matrix A:
 [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]] 

Matrix B:
 [[-2 -2  1]
 [ 0  1  1]]


In [44]:
A + B  # simply use the Python addition operator +


array([[ 0.        , -1.9       ,  0.        ],
       [ 3.        ,  1.2       ,  2.41421356]])

In [45]:
A - B  # simply use the Python subtraction operator -


array([[ 4.        ,  2.1       , -2.        ],
       [ 3.        , -0.8       ,  0.41421356]])

In [46]:
#Properties of matrix addition and multiplication by scalars

#function numpy.array_equal() allows to compare two arrays for both shape and element equality

# create a matrix 
C = np.array([[-2, 1, -1],
              [-2, 1, 1]])

In [47]:
# print the matrices
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C:\n", C)

Matrix A:
 [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]]
Matrix B:
 [[-2 -2  1]
 [ 0  1  1]]
Matrix C:
 [[-2  1 -1]
 [-2  1  1]]


In [48]:
#Distributivity of a scalar when adding two matrices

c = 2  # a scalar
np.array_equal(c * (A + B), (c * A) + (c * B))

True

In [49]:
#the == operator will compare the entries element-wise, and not the entire arrays at once
c * (A + B) == (c * A) + (c * B)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [50]:
#Associativity of matrix addition

np.array_equal(A + (B + C), (A + B) + C)

False

In [51]:
A + (B + C)

array([[-2.        , -0.9       , -1.        ],
       [ 1.        ,  2.2       ,  3.41421356]])

In [52]:
(A + B) + C

array([[-2.        , -0.9       , -1.        ],
       [ 1.        ,  2.2       ,  3.41421356]])

In [53]:
#under the hood, NumPy is making some approximations on the value of the last element 
#(computers don't have infinite memory to save all the decimal cases we need!). 
#Let's first round all the elements to a lower number of decimal cases, using .round(), 
#prior to the comparison made by numpy.array_equal. This way we ensure we are comparing 
#only up to a certain number of decimal cases.


np.array_equal((A + (B + C)).round(2), 
               ((A + B) + C).round(2))

True

In [54]:
#Transpose

print("Matrix A:\n", A)

Matrix A:
 [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]]


In [55]:
A_T = np.transpose(A)  # same as A.T
A_T

array([[ 2.        ,  3.        ],
       [ 0.1       ,  0.2       ],
       [-1.        ,  1.41421356]])

In [56]:
#Accessing rows and columns in 2D arrays

# 3x2 matrix represented as a list
a_list = [[1, 2], [3, 4], [5, 6]]

In [57]:
# the same 3x2 matrix represented by an array
a_array = np.array([[1, 2], [3, 4], [5, 6]])

In [58]:
a_list

[[1, 2], [3, 4], [5, 6]]

In [59]:
a_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
a_array.shape


(3, 2)

In [61]:
#Select a single row

a_list[0]  # access first list (first row)

[1, 2]

In [62]:
a_array[0]  # access first axis (first row)

array([1, 2])

In [63]:
#Select a single element

a_list[1][0]  # access first element of the second row (list)

3

In [64]:
a_array[1][0]  # access first element of the second row (numpy array) -- access rows on 1st axis, columns on 2nd axis


3

In [65]:
#The ndarray also supports another type of indexing, where we have one index per axis separated by commas (tuple)

a_array[1, 0]


3

In [66]:
#Subsetting rows and columns

b_array = np.arange(0, 5*5).reshape(5, 5)  # (5x5) matrix with integer values from 0 to 24
b_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
b_array[3:]  # access rows starting at the fourth row


array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
b_array[1:, 1]  # access second row and beyond, access second column


array([ 6, 11, 16, 21])

In [69]:
#slice principle a_list[start:stop:step]

b_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
b_array[
    1:4,  # 1st axis: access rows from the second (index 1) until the fourth (index 3)
    :-1  # 2nd axis: access all columns until the last one (excluded)
] 

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [71]:
b_array[
    2:8:2, # 1st axis: access rows starting at 3rd row (index 2), and each 2nd row after that
    3: # 2nd axis: access from the 4th column until the last
] 

array([[13, 14],
       [23, 24]])

In [72]:
#Concatenation

# create arrays of shape (2, 3)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]


In [73]:
np.concatenate((A, B), axis = 0)  # concatenate along axis 0 (rows)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
np.concatenate((A, B), axis = 1)  # concatenate along axis 1 (columns)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [75]:
# Iterating through arrays


a = np.array([[.0, .2, .4], [.6, .8, 1.]])
i = 1
for row in a:
    print(f"row {i}: {row}")
    i+=1

row 1: [0.  0.2 0.4]
row 2: [0.6 0.8 1. ]


In [76]:
# Boolean indexing


a = np.array([[-1, -.5, 0.2],
              [.5, 1, 1.5]])
a.shape

(2, 3)

In [77]:
#filter (keep only) the entries where the condition a[ij] > 0 is met

a_positives = a[a > 0]
a_positives

array([0.2, 0.5, 1. , 1.5])

In [78]:
a > 0 # this is the boolean mask we used above


array([[False, False,  True],
       [ True,  True,  True]])

In [79]:
a_positives.shape


(4,)

In [80]:
#the expression a>0 is itself an array, more specifically, a boolean array or boolean mask,

a_bool = a > 0
a_bool

array([[False, False,  True],
       [ True,  True,  True]])

In [81]:
#Using .dtype we can confirm the type of this array

a_bool.dtype


dtype('bool')

In [82]:
#you can  use the mask above on another array

b = np.array([[0, 1, 2],
              [3, 4, 5]])
b[a_bool]

array([2, 3, 4, 5])

In [83]:
#The ~ operator

d = np.array([[-1, -2, -3, -4], 
              [1, 2, 3, 4]])
d

array([[-1, -2, -3, -4],
       [ 1,  2,  3,  4]])

In [84]:
#mask

d > 0

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [85]:
#create a reverse mask where d > 0 is not true, we can use the negation operator, ~

~(d > 0)


array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [86]:
d <= 0


array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [87]:
print("d[d>0] = ", d[d>0])


d[d>0] =  [1 2 3 4]


In [88]:
print("d[~(d>0)] = ", d[~(d>0)])



d[~(d>0)] =  [-1 -2 -3 -4]


In [89]:
print("d[d<=0] = ", d[d<=0])


d[d<=0] =  [-1 -2 -3 -4]


In [90]:
#Copying numpy arrays .copy()

a = np.array([[1], [2]])
b = a.copy()  # GOOD PRACTICE

In [91]:
a = np.array([[1], [2]])
b = a  # BAD PRACTICE

In [92]:
# multiply two matrices using np.matmul()

# 2D array to represent A
A = np.array([[-1, 2],
              [4, 6]])
# 2D array to represent B
B = np.array([[0, 3, 6],
              [-2, 0, -1]])


#both are 2D arrays

# numpy.matmul() to multiply A by B
C = np.matmul(A, B)
C

array([[ -4,  -3,  -8],
       [-12,  12,  18]])

In [93]:
#using 2-D array
# multiplying (2x1) column vector by (1x2) row vector using 2D arrays
np.matmul(np.array([[0],
                    [1]]),  # 2D array
          np.array([[-1, 2]]))  # 2D array



array([[ 0,  0],
       [-1,  2]])

In [94]:

#using 1-D array

# multiplying (2x1) column vector by (1x2) row vector using 2D array and 1D array, respectively
np.matmul(np.array([0, 1]),  # 1D array
          np.array([-1, 2]))  # 1D array

2

In [95]:
#using 2-D and 1-D array

x = np.array([[0],[1]])  # 2D array, matrix 2x1 (column vector)
y = np.array([-1, 2])  # 1D array, row vector 1x2
try:
    np.matmul(x, y)
except Exception as e: 
    print("ValueError:", e)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)


In [96]:
print("x.shape:", x.shape)
print("y.shape:", y.shape)

x.shape: (2, 1)
y.shape: (2,)


In [97]:
#multiplying in the reverse order (y as first argument and x as second) will work. 
#In this case, our first argument has shape (2,), which will be converted to (1,2)

np.matmul(y, x)

array([2])

In [98]:
#The * operator is not to be used for matrix multiplication!!

In [99]:
#Using numpy.matmul() versus numpy.dot()

# 2D array to represent A
A = np.array([[-1, 2],
              [4, 6]])
# 2D array to represent B
B = np.array([[0, 3],
              [-2, 0]])

In [100]:
#it works, however NumPy advises to use numpy.matmul() in the case of 2-D arrays
np.dot(A, B)

array([[ -4,  -3],
       [-12,  12]])

In [101]:
#determine the inverse of a matrix using  numpy.linalg.inv()

# a non-invertible square matrix
A = np.array([[1, 2],
              [2, 4]])
A

# try to determine the inverse using NumPy
try:
    np.linalg.inv(A)
except Exception as e:  # NumPy is smart, so it throws an error because A is not invertible
    print("LinAlgError:", e)

LinAlgError: Singular matrix


In [102]:
# an invertible matrix
B = np.array([[0, 2],
              [-4, 1]])
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.125, -0.25 ],
       [ 0.5  ,  0.   ]])

In [103]:
#let's check that multiplying B by B_inv actually yields the identity


# multiply B by B_inv
print("B multiplied by B_inv:\n", np.matmul(B, B_inv))

# multiply B_inv by B (because we're paranoid and insane, and doubt the Mathematicians)
print("B_inv multiplied by B:\n", np.matmul(B_inv, B))

B multiplied by B_inv:
 [[1. 0.]
 [0. 1.]]
B_inv multiplied by B:
 [[1. 0.]
 [0. 1.]]


In [104]:
#Additional NumPy methods

#ndarray.max() and ndarray.min()

# a 3x3 square matrix
A = np.array([[1, -1, 0],
              [2, -2, 3],
              [6, 0, -1]])
A

array([[ 1, -1,  0],
       [ 2, -2,  3],
       [ 6,  0, -1]])

In [105]:
# using axis=1 we get the maximum value per row of A
A.max(axis=1)

array([1, 3, 6])

In [106]:
# using axis=0 we get the maximum value per column of A
A.max(axis=0)

array([6, 0, 3])

In [107]:
# if we don't specify the axis, it will use the default value axis=None (for v1.20 of NumPy)
# meaning it will return the maximum value in the entire 2D array
A.max()

6

In [108]:
# using axis=1 we get the minimum value per row of A
A.min(axis=1)

array([-1, -2, -1])

In [109]:
# using axis=0 we get the minimum value per column of A
A.min(axis=0)

array([ 1, -2, -1])

In [110]:
# if we don't specify the axis, it will use the default value axis=None (for v1.20 of NumPy)
# meaning it will return the minimum value in the entire 2D array
A.min()

-2

In [111]:
#Let's see what would happen with a 2D array A that has two maximum values (number 3) on the last column:

# 2D array with 2 equal maximum values in 3rd colum
A = np.array([[1, -1, 3],
              [2, 2, 3],
              [6, 0, -1]])

# using axis=0 we get the maximum value per column of A
A.max(axis=0)

array([6, 2, 3])

In [112]:
#NumPy chooses one of the repeated values.

In [113]:
#ndarray.sort() and numpy.sort()

# ndarray.sort() allows us to sort an array in-place. We also need to choose the axis along which to sort

A

array([[ 1, -1,  3],
       [ 2,  2,  3],
       [ 6,  0, -1]])

In [114]:
A.sort(axis=1)  # this will change the array in-place!!
A

array([[-1,  1,  3],
       [ 2,  2,  3],
       [-1,  0,  6]])

In [115]:
#Each row was sorted in ascending order from the lowest to the highest value.

In [116]:
#If you don't want your array to be changed in-place, you can use numpy.sort() instead:

A = np.array([[1, -1, 3],
              [2, 2, 3],
              [6, 0, -1]])
np.sort(A) # sort along the last axis (default is axis=-1)

array([[-1,  1,  3],
       [ 2,  2,  3],
       [-1,  0,  6]])

In [117]:
np.sort(A, axis=None)  # sort the flattened array (array reshaped to 1 dimension)

array([-1, -1,  0,  1,  2,  2,  3,  3,  6])

In [118]:
np.sort(A, axis=0)  # sort along the first axis

array([[ 1, -1, -1],
       [ 2,  0,  3],
       [ 6,  2,  3]])

In [119]:
#If you wanted to sort in reverse order


-np.sort(-A, axis=0)  # sort along the first axis

array([[ 6,  2,  3],
       [ 2,  0,  3],
       [ 1, -1, -1]])

In [120]:
#ndarray.sum()

#to find the sum of a matrix columns and/or rows

A

array([[ 1, -1,  3],
       [ 2,  2,  3],
       [ 6,  0, -1]])

In [121]:
# The default, axis=None, will sum all of the elements of the input array
print(A.sum())

15


In [122]:
B = np.array([[[1], [2]], [[3], [4]]])
B.ndim

3

In [123]:
B.sum()

10

In [124]:
A.sum(axis=0)  # Sum elements along axis=0 (sum elements in each column)

array([9, 1, 5])

In [125]:
A.sum(axis=1)  # Sum elements along axis=1 (sum elements in each row)

array([3, 7, 5])

In [128]:
mat_1 = np.array([[44, 68], [-37, 14], [85, -48], [92, -46], [-42, 63], [-42, 63], [-35, 75]])
mat_2 = np.array([[22, -40, 95, 62], [10, -42, 98, 19]])


C = np.matmul(mat_1, mat_2)
C

array([[ 1648, -4616, 10844,  4020],
       [ -674,   892, -2143, -2028],
       [ 1390, -1384,  3371,  4358],
       [ 1564, -1748,  4232,  4830],
       [ -294,  -966,  2184, -1407],
       [ -294,  -966,  2184, -1407],
       [  -20, -1750,  4025,  -745]])

# Decrypt Message

In [1]:
allowed_characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ "

def clean_message(text_):
    
    ## convert to uppercase
    text_upper = text_.upper()
    
    ## remove characters not in allowed_characters using list comprehension
    text_list_ = [char for char in text_upper if char in allowed_characters]
    
    ## join the characters back together into one string
    text_ = ''.join(text_list_)
    
    ## remove extra whitespaces (hint: use .join() and .split())
    text_ = " ".join(text_.split())
    
    ## we'll add one extra whitespace at the end if the number list length is odd
    ## we need this to be able to build an Nx2 matrix on the next steps
    if len(text_) % 2 != 0:
        text_ += " "
    
    return text_


In [2]:
def get_numlist(text_):
    
    # empty list to save numbers
    numlist_ = []
    
    # iterate through each character in the clean message
    for char in text_:
        if char == " ": # append 26, if it is a whitespace
            numlist_.append(26)
        else: # append 0-25 number to the corresponding to A-Z letter
            numlist_.append(ord(char) - 65)
    
    # return message as list of number
    return numlist_

# test it!
numbers_msg = get_numlist("I LOVE LINEAR ALGEBRA")
print("First five numbers in the message:", numbers_msg[:5])

First five numbers in the message: [8, 26, 11, 14, 21]


In [3]:
# read a number list into its original message
def get_text(numlist_):
    return "".join([chr(i + 65) if i != 26 else " " for i in numlist_])

# revert back to text message
print(get_text(numbers_msg))

I LOVE LINEAR ALGEBRA


In [4]:
def cipher_matrix(numberlist_):
    
    ## convert numberlist_ into 1D array
    num_array_ = np.array(numberlist_)
    
    ## reshape num_array to shape (len(numberlist_) // 2, 2)
    row_number = int(len(numberlist_)/2)
    matrix_array = num_array_.reshape(row_number, 2)
    
    return matrix_array


In [5]:
def encrypt_matrix(cipher_, key_):
    
    ## write a try except to check if the key_ is invertible - if it's not, the function should return None
    try:
        np.linalg.inv(key_)
    except Exception as e:
        return None
    
    ## multiply cipher_ by key_ and return the result
    return np.matmul(cipher_, key_)
    


In [6]:
def encrypt_message(message_, key_matrix_):
    
    ## clean message
    msg_ = clean_message(message_)
    
    ## convert message to list of numbers
    numlist_ = get_numlist(msg_)
    
    ## convert list of numbers to cipher matrix
    cipher_matrix_ = cipher_matrix(numlist_)
    
    ## encrypt cipher_matrix_
    encrypted_matrix_ = encrypt_matrix(cipher_matrix_, key_matrix_)
    
    return encrypted_matrix_

In [7]:
def get_text(numlist_):
    return "".join([chr(i + 65) if i != 26 else " " for i in numlist_])

In [8]:
def decrypt_message(encrypted_matrix_, key_matrix_):
    
    ## determine the inverse of the key_matrix_
    key_matrix_inv_ = np.linalg.inv(key_matrix_)
    
    ## determine the message matrix (matrix A in the cell above)
    original_matrix_ = np.matmul(encrypted_matrix_, key_matrix_inv_)
    
    ## convert all elements in array to integers (check numpy documentation!)
    original_matrix_ = original_matrix_.astype(int)
    
    ## flatten original_matrix (check numpy documentation!!)
    original_matrix = original_matrix_.flatten()
    
    ## use function get_text() to convert the matrix into a message
    original_message_ = get_text(original_matrix)
    
    return original_message_

In [11]:
#Exercise 2.3 (ungraded)
import numpy as np
# Try to find the meaning behind the matrix below
hidden_message = np.array([[42, 25], [34, 21], [28, 38], [ 8, 17], [ 0, 26], [52, 45], [14, 26], [52, 30],
                           [ 6, 14], [36, 36], [52, 26], [34, 32], [30, 19], [ 4, 28], [40, 34], [36, 35],
                           [52, 30], [36, 26], [ 0, 26], [ 8, 26], [28, 32], [ 8, 16]])

key_matrix = np.array([[0, 1], [2, 1]])  # here's the key!
decrypt_message(hidden_message, key_matrix)

'EVERYONE AT THE LDSSA PREP COURSE IS AWESOME'